databases:
  - name: elms-db
    databaseName: elms_db
    user: elms_user
    plan: free

services:
  - type: web
    name: elms-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_HOSTBUILDER_CONFIG_RELOAD_ON_CHANGE
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: elms-db
          property: connectionString
      - key: JWT_KEY
        generateValue: true
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
    healthCheckPath: /swagger
